import { blogPosts } from './blogData.js';

export const SITE_URL = 'https://www.obbacalculators.com';

export const pageSeoByPath = {
  '/': {
    title: 'Best Paycheck & Tax Calculators 2026 | OBBA',
    description: 'See your real take-home pay in seconds with OBBA Calculators - paycheck, salary, overtime, state taxes, and money-saving tools in one modern view.',
    keywords: 'Tax Calculator',
    canonicalPath: '/',
  },
  '/overtime': {
    title: 'Overtime Calculator, Time and a Half & Double Time Pay | CheckYourPays',
    description: 'Calculate your overtime pay, time and a half, double time, and total gross pay — from your hourly rate and hours worked. Free, instant, no sign-up.',
    keywords: 'Overtime Calculator',
    canonicalPath: '/overtime',
  },
  '/salary-calculator': {
    title: 'Salary Calculator 2026 — See Your Real Take-Home Pay | CheckYourPays',
    description: 'Turn your annual, monthly, or hourly salary into what actually lands in your account. Free salary calculator with federal, state, and FICA taxes — no sign-up.',
    keywords: 'Salary calculator',
    canonicalPath: '/salary-calculator',
  },
  '/paycheck-calculator': {
    title: 'Paycheck Calculator — Hourly & Overtime Take-Home Pay | CheckYourPays',
    description: 'Calculate your paycheck from an hourly wage, including overtime and bonus pay. Free paycheck calculator with a full pay stub breakdown — no sign-up.',
    keywords: 'Paycheck Calculator',
    canonicalPath: '/paycheck-calculator',
  },
  '/states': {
    title: 'State Paycheck Calculators Coming Soon | CheckYourPays',
    description: 'State paycheck calculators are being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'State paycheck calculators',
    canonicalPath: '/states',
    robots: 'noindex,follow',
  },
  '/texas-paycheck-calculator': {
    title: 'Texas Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Texas paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Texas Paycheck Calculator',
    canonicalPath: '/texas-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/florida-paycheck-calculator': {
    title: 'Florida Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Florida paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Florida Paycheck Calculator',
    canonicalPath: '/florida-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/california-paycheck-calculator': {
    title: 'California Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The California paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'California Paycheck Calculator',
    canonicalPath: '/california-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/illinois-paycheck-calculator': {
    title: 'Illinois Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Illinois paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Illinois Paycheck Calculator',
    canonicalPath: '/illinois-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/washington-paycheck-calculator': {
    title: 'Washington Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Washington paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Washington Paycheck Calculator',
    canonicalPath: '/washington-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/indiana-paycheck-calculator': {
    title: 'Indiana Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Indiana paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Indiana Paycheck Calculator',
    canonicalPath: '/indiana-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/virginia-paycheck-calculator': {
    title: 'Virginia Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Virginia paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Virginia Paycheck Calculator',
    canonicalPath: '/virginia-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/hawaii-paycheck-calculator': {
    title: 'Hawaii Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Hawaii paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Hawaii Paycheck Calculator',
    canonicalPath: '/hawaii-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/nebraska-paycheck-calculator': {
    title: 'Nebraska Paycheck Calculator Coming Soon | CheckYourPays',
    description: 'The Nebraska paycheck calculator is being rebuilt and will return soon. Use the active salary, paycheck, and overtime calculators now.',
    keywords: 'Nebraska Paycheck Calculator',
    canonicalPath: '/nebraska-paycheck-calculator',
    robots: 'noindex,follow',
  },
  '/faq': {
    title: 'FAQ - OBBBA Tax Calculators',
    description: 'Read frequently asked questions for OBBBA Tax Calculators covering overtime, salary, paycheck, Texas, and Florida paycheck estimation workflows.',
    keywords: 'How to use calculators, paycheck calculator guide, frequently asked questions',
    canonicalPath: '/faq',
  },
  '/faqs': {
    title: 'FAQ - OBBBA Tax Calculators',
    description: 'Read frequently asked questions for OBBBA Tax Calculators covering overtime, salary, paycheck, Texas, and Florida paycheck estimation workflows.',
    keywords: 'How to use calculators, paycheck calculator guide, frequently asked questions',
    canonicalPath: '/faq',
  },
  '/about-us': {
    title: 'About Us - OBBBA Tax Calculators',
    description: 'Learn about OBBBA Tax Calculators, our estimate methodology, active tools, SEO-focused resources, and planning scope for federal payroll calculations.',
    canonicalPath: '/about-us',
  },
  '/privacy-policy': {
    title: 'Privacy Policy - OBBBA Tax Calculators',
    description: 'Review the OBBBA Tax Calculators Privacy Policy explaining data use, security practices, calculator input handling, and privacy rights.',
    canonicalPath: '/privacy-policy',
  },
  '/terms-conditions': {
    title: 'Terms & Conditions - OBBBA Tax Calculators',
    description: 'Read Terms & Conditions for OBBBA Tax Calculators including estimate limitations, liability terms, acceptable use, and legal scope.',
    canonicalPath: '/terms-conditions',
  },
  '/contact-us': {
    title: 'Contact Us - OBBBA Tax Calculators',
    description: 'Contact OBBBA Tax Calculators for support, corrections, policy requests, and calculator feedback across overtime, salary, and paycheck tools.',
    canonicalPath: '/contact-us',
  },
  '/blogs': {
    title: 'Knowledge Hub - Tax Calculator Guides & Articles',
    description: 'Read guides on how to use tax calculators, understand payroll deductions, federal income tax brackets, and overtime calculations.',
    keywords: 'How to use calculators',
    canonicalPath: '/blogs',
    robots: 'noindex,follow',
  },
  ...Object.fromEntries(blogPosts.map((post) => [
    `/blogs/${post.slug}`,
    {
      title: `${post.title} | OBBA Calculators`,
      description: post.description,
      canonicalPath: `/blogs/${post.slug}`,
      robots: 'noindex,follow',
    },
  ])),
};

export const breadcrumbLabelsByPath = {
  '/': 'Home',
  '/overtime': 'No Tax on Overtime Calculator',
  '/salary-calculator': 'Salary Calculator',
  '/paycheck-calculator': 'Paycheck Calculator',
  '/states': 'State Paycheck Calculators',
  '/texas-paycheck-calculator': 'Texas Paycheck Calculator',
  '/florida-paycheck-calculator': 'Florida Paycheck Calculator',
  '/california-paycheck-calculator': 'California Paycheck Calculator',
  '/illinois-paycheck-calculator': 'Illinois Paycheck Calculator',
  '/washington-paycheck-calculator': 'Washington Paycheck Calculator',
  '/indiana-paycheck-calculator': 'Indiana Paycheck Calculator',
  '/virginia-paycheck-calculator': 'Virginia Paycheck Calculator',
  '/hawaii-paycheck-calculator': 'Hawaii Paycheck Calculator',
  '/nebraska-paycheck-calculator': 'Nebraska Paycheck Calculator',
  '/faq': 'FAQ',
  '/faqs': 'FAQ',
  '/about-us': 'About Us',
  '/privacy-policy': 'Privacy Policy',
  '/terms-conditions': 'Terms & Conditions',
  '/contact-us': 'Contact Us',
  '/blogs': 'Knowledge Hub',
  ...Object.fromEntries(blogPosts.map((post) => [`/blogs/${post.slug}`, post.title])),
};
